### ISSUE TITLE
Panic encountered if invitation is created before agency restart

### ISSUE THREAD

**Issue by lauravuo-techlab** [findy-network/findy-agent#160]
"invitations aren't transported thru these anymore" panic is encountered if invitation is created before agency restart

```
core_1      | I0110 11:43:28.645758      26 server.go:124] ===== Aries TRANSPORT =====POST
core_1      | I0110 11:43:28.645820      26 server.go:125] http://localhost:8080/a2a/EG7sSE9ddCarL5bKP3yjm5/EG7sSE9ddCarL5bKP3yjm5/Tfo94nCBaShcJ4WGqrK1h7/18d40c61-a9b4-4100-accb-582885fdf1c6
core_1      | I0110 11:43:28.645846      26 server.go:126] =====
core_1      | E0110 11:43:28.650220      26 server.go:156] invitations aren't transported thru these anymore
core_1      | goroutine 121 [running]:
core_1      | runtime/debug.Stack(0x9c, 0x0, 0x0)
core_1      |   /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
core_1      | runtime/debug.PrintStack()
core_1      |   /usr/local/go/src/runtime/debug/stack.go:16 +0x25
core_1      | github.com/findy-network/findy-agent/server.transportPL.func2(0xc54ac0, 0xeb2570)
core_1      |   /work/server/server.go:157 +0x90
core_1      | github.com/lainio/err2.CatchAll(0xdfb830, 0xdfb838)
core_1      |   /go/pkg/mod/github.com/lainio/err2@v0.7.0/err2.go:152 +0xa9
core_1      | panic(0xc54ac0, 0xeb2570)
core_1      |   /usr/local/go/src/runtime/panic.go:965 +0x1b9
core_1      | github.com/findy-network/findy-agent/server.transportPL(0xc0001d6d80, 0xc0000ce900, 0x705, 0x900)
core_1      |   /work/server/server.go:173 +0x438
core_1      | created by github.com/findy-network/findy-agent/server.protocolTransport
core_1      |   /work/server/server.go:110 +0x18b
core_1      | I0110 11:43:28.655088      26 psm.go:56] grpc Waiting state in 18d40c61-a9b4-4100-accb-582885fdf1c6
```

Apparently this functionality is currently a feature: invitation placeholders are stored in memory only, not persisted. Perhaps it will be a good time to refactor and fix this functionality in the future if we will get an alternative storage to indy wallet.

**Comment by lauravuo-techlab** [comment]
This is fixed now that we have the new storage in use, and preallocated connections are always stored when created.
